# Documentation:
# http://flutter.dev/go/i18n-user-guide
arb-dir: lib/l10n
template-arb-file: test_en.arb
synthetic-package: false
output-class: TestLocalizations
output-localization-file: test_localizations.dart
preferred-supported-locales: "en"
use-deferred-loading: false
untranslated-messages-file: lib/l10n/missing_localizations.json
nullable-getter: false
header: "// ignore_for_file: unnecessary_brace_in_string_interps"
