name: test_task
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_slidable: ^3.1.0
  intl: ^0.19.0
  auto_route: ^8.2.0
  figma_squircle: ^0.5.3
  get_it: ^7.6.0
  injectable: ^2.1.1
  sizer: ^2.0.15
  logger: ^2.0.2+1
  flutter_bloc: ^8.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.7
  carousel_slider: ^4.1.1
  # flutter_webview_plugin: ^0.4.0
  auto_size_text: ^3.0.0
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^11.0.0
  flutter_spinkit: ^5.1.0
  json_annotation: ^4.7.0
  permission_handler: ^11.1.0
  equatable: ^2.0.5
  uuid: ^4.1.0
  lottie: ^3.1.2
  flutter_keyboard_visibility: ^6.0.0
  collection: ^1.16.0
  jiffy: ^6.1.0
  package_info_plus: ^8.0.0
  flutter_staggered_grid_view: ^0.7.0
  swipeable_page_route: ^0.4.3
  recase: ^4.1.0
  flutter_html: ^3.0.0-alpha.6
  # This version is needed to use
  # because of issue [https://github.com/flutter/flutter/issues/82602]
  fluttertoast: ^8.1.2
  flutter_image_compress: ^2.0.3
  google_fonts: ^6.1.0
  retrofit: ^4.2.0
  dio: ^5.6.0
  jwt_decoder: ^2.0.1
  google_sign_in: ^6.2.1
  device_preview: ^1.1.0
  email_auth: ^2.0.0
  email_otp: ^3.0.1
  analyzer: ^6.2.0
  http: ^1.1.0
  audioplayers: ^5.2.0
  syncfusion_flutter_charts:
  flutter_sticky_header: ^0.6.5
  path_provider: ^2.1.1
  path: ^1.8.3
  timer_count_down: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.2.1
  injectable_generator: ^2.1.5
  flutter_gen_runner: ^5.0.2
  flutter_native_splash: ^2.2.11
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.5.1
  retrofit_generator: ">=7.0.0 <8.0.0"
  change_app_package_name: ^1.1.0
  serverpod_cli: ^2.0.2
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
